SET( DagQtTest_SRC DagQtTest.cpp )
ADD_EXECUTABLE( DagQtTest ${DagQtTest_SRC} )
IF (UNIX)
LIST(APPEND LUA_LIBRARIES dl)
ENDIF(UNIX)
TARGET_LINK_LIBRARIES( DagQtTest PRIVATE dagbase GTest::gtest_main;GTest::gmock)
INSTALL(TARGETS DagQtTest RUNTIME DESTINATION bin)
SET_TARGET_PROPERTIES( DagQtTest PROPERTIES INSTALL_RPATH "${CMAKE_INSTALL_RPATH};${CMAKE_INSTALL_PREFIX}/lib" )
